language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy: 
  provider: heroku
  api_key: 
    secure: Zv1QTJpE58ZGW+0+TyBGKlBLK5uK4Nawngc7Tp/5yPau60g3RADVCM2Is1gRGmqqVfqQjB2TXfH7h32lAItYin8bjmZdA4eacQFuMSkBUqGPaPGr79Z4WLpFPMXPhSD8Amn1H8OATPySPzqlxojmhdEmz3BzkL9DEmkQYMFgR+MpURyWHyy0rS9AAIYEB6oWwi4M0qdKyiyFh1lcKFIxtHsdhdl62Dtj02UBvE7ykYtF9cPmnrtM37NUaqPwNQMnBzrtQZmbNsX0ppA7IBXSk+qlXLCZKtbChqPyf4EC6wpkpIklzgsilIq6bvFmmes2umBvUV+x0UihnFzK3rbUPb4W4vV8DsxV26U01h8FpKobjUwlnErq59smu2G6Ly1VjNiNwwvbo1Ht+1035PVjetixYw1CmC9CFXbaHYb2VONdHOyQTrULNECDiIbTL+ssn+CmzFECfjbAkyteApSwA0yQX8rIdEZ8lfpjOr5Oa1Kg2P59YQKwEt1f+J4YW3MWyKPIuoJbjN6FvZnO8jAPj8MHCt9EqxuikT+cQ03+IOOPtWmHNQYleHfOBJFGzQgej+8edlHO7cCqfUuevedR2Ktm8ZZAOV0gixcMFmEF1JisH6xICbTsdIO6Rvl0t69TzShj/fcO87t7HvEN2fDXnN9g5FqacpG5Jq0G0Z+1Ra8=
  app: vast-dusk-40974