language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: j1Ck0X5HPyWF4V+SylZ0FUFuOCwAVK30xTUK7xnLb97vtEG8rVs8NZ9oeJGu6V49kXhidZuB/tsKTbDyIcX2HCVI87rqT3ujvVqiuCEOYBQ8EuaQzdzGb4C1+Clrwu0OGk59842MsczfXVC1Qs6h/FCCAX+J/Fq+hieXy17lx+x8XHjdxToF7O13yqCiWqsPvV8E0dz/bjS8Kj/8x86fN74dghokFEoeyJn4LqNskf23NGvZQKjU1bj4HczYgrLNenRuwhxA3PLgPd78YYpp1iSNYfq9X+6ANMNNIliecNrebblUwXRVi0t7XctAoYkqb2M5gxl3YFdCrNoVLRYfAH6K1WZunL/Hu8ohVycmAV4BEx2k97+BvsvAsoiGq/rWgR+tygncBHMDTF12v4ipkrh65m+ame+5yxRrYB3OwDwRqurx1pcghG3G/tdnBedq7O8fngYrK3romt1fkAgD4UFwpFXocD7MyDJyCXjnSRhEoUKhPsOtQXrMInAk+yTBLPuyWguLt3tPOTPw5gfqkjQm5EsG42wYWk32exxrgbCiB7RQ0jM5/LP8W/eymIM46MdZFrWmINgjgRMNrTq9oiuYNF5ZxR9/8m1HmhZ0VSEwD90CKAgW1y77oFPi6TMI6nbloF5tQrkhK5C4UPvhP90dUMUrlfMzzfuZK7QtDwM=
  app: vast-dusk-40974
  on:
    repo: spoofBlue/HotAndColdWithTesting
