language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: NVskT5WXXIK+jDNVqQitypxz5nBXiE5UVCZjgEzvQ/J7FTbgFyanez5Y6EBXcPUsijJZ7ZS/Pa3cZiiJn7fQfD8gNbZuCTjmvKN1VCk/48toq2sdXcIYldV+bHC2d4jwZtQzebga6L2WqYTferTS4YYFW1gvkJiV0U+AwGxE2H8thdPPS+GoXAqcfXFO5EV8Kydf7/mVU4s02PkibSxfb1fQr+mydDgvDmLtF07cvCrbQsNpjCVfxkkWg9F6yMhlxHZkhAV1TqEnI3VUuUgQSASCed3veunAmDcVOyERVhUTwxj/8wqc7VAhyM0jJpY0jFo7xnKo+ZAfJND8KGRA3Xa9yNYuXqFcHsW2x4xRBLOZuBIoJdzOBW5qyiiG3mrQPJVl+pc5loP38uRpNv5bPQy/kV+JZz2QXwXaepj8bdXTOxhoZGjHmPDsahVapahfX6FETOd+p2hxlpBTWAXMtgrB6JlMcKrYYqVPYmcYACFpYyMW5qGu4BjKNpxJiPfaxlqVFysh4OQePHqCMBsExi7xu2REr/YVzp2kaPs7r3j/tT6YfNH5/gyj2mjs5IXyAYJP4rxiBiJqDl+nI60yixamCe/K2HKteTTT7ZK2E7Bd2hEznKy5WIagEqS/naodbSKU3KnGorj/Z7wzGuABLovY7lsh21OLiM54skyG9xg=
  app: vast-dusk-40974
  on:
    repo: spoofBlue/HotAndColdWithTesting
